site_name: System Principles

dev_addr: localhost:9201

theme:
  name: material

nav:
  - Home: index.md
  - Principles:
    - Index: principles/index.md
    - Designing: principles/designing.md
    - Modeling: principles/modeling.md
    - Structuring: principles/structuring.md
    - Implementing: principles/implementing.md
    - Verifying: principles/verifying.md
    - Presenting: principles/presenting.md
